// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The body of every error response: `{"error": {"code": "...", "message": "..."}}`.
 */
export type ErrorBody = { error: ErrorDetail, };

/**
 * Machine-readable error code. Exported to TypeScript as a string union.
 */
export type ErrorCode = "validation_error" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "internal_error";

export type ErrorDetail = { code: ErrorCode, message: string, };

export type LoginRequest = { email: string, password: string, };

export type RegisterRequest = { email: string, display_name: string, password: string, };

/**
 * Public view of a user. Never expose `users::Model` directly: it carries the
 * password hash.
 */
export type UserResponse = { id: string, email: string, display_name: string, created_at: string, };
